### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by wendellm** [teux/ng-cache-loader#14]
I have

    <ul class="list-unstyled padding-left-15 padding-right-15" ui-sortable="feed.sortableOptions" ng-    model="feed.items">
   	<li ng-repeat="item in feed.items" style="margin-bottom:0px" ng-if="!(item.state==0)">
		<div ng-include="item.name" />
	</li>
</ul>

and this

    require("ng-cache?!components/widgets/todo.html");
    feed.items.push("todo.html");

and finally this;

    { test: /\.html$/, loader: "ng-cache?prefix=[dir]/[dir]" },

It works todo.html gets rendered perfectly but I get wrapped in a span before my html gets rendered the following text;

    var v1="

and after todo is rendered on screen wrapped in a span I get the following:
     
    "; window.angular.module(["ng"]).run(["$templateCache",function(c)    {c.put("components/widgets/todo.html", v1)}]); module.exports=v1;

What's up with that? Am I doing something wrong?

**Comment by teux** [comment]
I think you should use either require or config for configuring loaders, not both. Otherwise webpack calls ng-cache twice. The first result is passed to the second call. But it is not html.

html => first call => javascript => second call => weird

Please see also https://webpack.github.io/docs/using-loaders.html#loaders-in-require

**Comment by teux** [comment]
I added a [note](https://github.com/teux/ng-cache-loader#usage) about this.

**Comment by wendellm** [comment]
If I removed the ng-cache?! from the require statement it works thanks, wonder why I missed something that obvious.
